/*
 *  SPDX-License-Identifier: Apache-2.0
 *
 *  Copyright The original authors
 *
 *  Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
 */
package dev.hardwood.internal.predicate.codegen;

import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.List;

import javax.annotation.processing.ProcessingEnvironment;
import javax.tools.Diagnostic;
import javax.tools.JavaFileObject;

/// Walks the 20-tuple eligibility matrix and emits one source file per
/// `(tuple, access mode)` — 40 generated `Fused…` classes total. All are
/// package-private in `dev.hardwood.internal.predicate` so they can call
/// the package-private helpers on [RecordFilterCompiler].
final class MatrixEmitter {

    private static final String PACKAGE = "dev.hardwood.internal.predicate";

    private final ProcessingEnvironment env;

    MatrixEmitter(ProcessingEnvironment env) {
        this.env = env;
    }

    void emitAll() {
        try {
            for (Tuple tuple : matrix()) {
                emit(tuple, /* named */ false);
                emit(tuple, /* named */ true);
            }
        } catch (IOException e) {
            env.getMessager().printMessage(Diagnostic.Kind.ERROR,
                    "Failed to emit fused matchers: " + e.getMessage());
            throw new RuntimeException(e);
        }
    }

    private static List<Tuple> matrix() {
        List<Tuple> out = new ArrayList<>();
        // AND closed/half-open interval — 4 op-pairs × 3 types = 12.
        for (PrimType t : List.of(PrimType.INT, PrimType.LONG, PrimType.DOUBLE)) {
            out.add(new Tuple(t, Connective.AND, Op.GTE, Op.LTE));
            out.add(new Tuple(t, Connective.AND, Op.GT, Op.LT));
            out.add(new Tuple(t, Connective.AND, Op.GTE, Op.LT));
            out.add(new Tuple(t, Connective.AND, Op.GT, Op.LTE));
        }
        // OR outside-interval — 2 op-pairs × 3 types = 6.
        for (PrimType t : List.of(PrimType.INT, PrimType.LONG, PrimType.DOUBLE)) {
            out.add(new Tuple(t, Connective.OR, Op.LT, Op.GT));
            out.add(new Tuple(t, Connective.OR, Op.LTE, Op.GTE));
        }
        // OR equality 2-element IN list — 1 op-pair × 2 types = 2 (double excluded; NaN equality).
        out.add(new Tuple(PrimType.INT, Connective.OR, Op.EQ, Op.EQ));
        out.add(new Tuple(PrimType.LONG, Connective.OR, Op.EQ, Op.EQ));
        return out;
    }

    private void emit(Tuple tuple, boolean named) throws IOException {
        String simpleName = tuple.className(named);
        String qualifiedName = PACKAGE + "." + simpleName;
        JavaFileObject file = env.getFiler().createSourceFile(qualifiedName);
        try (PrintWriter w = new PrintWriter(file.openWriter())) {
            writeSource(w, tuple, named, simpleName);
        }
    }

    private static void writeSource(PrintWriter w, Tuple tuple, boolean named, String simpleName) {
        String prim = tuple.type.primName;
        String getter = "get" + tuple.type.boxedName;
        String connectiveOp = tuple.connective == Connective.AND ? "&&" : "||";
        String cmpA = tuple.type.compare("v", "va", tuple.opA);
        String cmpB = tuple.type.compare("v", "vb", tuple.opB);
        w.print(named
                ? namedSource(simpleName, prim, getter, cmpA, connectiveOp, cmpB)
                : indexedSource(simpleName, prim, getter, cmpA, connectiveOp, cmpB));
    }

    private static String indexedSource(String simpleName, String prim, String getter,
            String cmpA, String connectiveOp, String cmpB) {
        return """
                /*
                 *  SPDX-License-Identifier: Apache-2.0
                 *
                 *  Copyright The original authors
                 *
                 *  Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
                 */
                // Generated by FusedMatcherProcessor — do not edit.
                package %1$s;

                import dev.hardwood.reader.RowReader;
                import dev.hardwood.row.StructAccessor;

                final class %2$s implements RowMatcher {
                    private final int idx;
                    private final %3$s va;
                    private final %3$s vb;

                    %2$s(int idx, %3$s va, %3$s vb) {
                        this.idx = idx;
                        this.va = va;
                        this.vb = vb;
                    }

                    @Override
                    public boolean test(StructAccessor row) {
                        RowReader r = (RowReader) row;
                        if (r.isNull(idx)) {
                            return false;
                        }
                        %3$s v = r.%4$s(idx);
                        return %5$s %6$s %7$s;
                    }
                }
                """.formatted(PACKAGE, simpleName, prim, getter, cmpA, connectiveOp, cmpB);
    }

    private static String namedSource(String simpleName, String prim, String getter,
            String cmpA, String connectiveOp, String cmpB) {
        return """
                /*
                 *  SPDX-License-Identifier: Apache-2.0
                 *
                 *  Copyright The original authors
                 *
                 *  Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
                 */
                // Generated by FusedMatcherProcessor — do not edit.
                package %1$s;

                import dev.hardwood.row.StructAccessor;

                final class %2$s implements RowMatcher {
                    private final String[] path;
                    private final String name;
                    private final %3$s va;
                    private final %3$s vb;

                    %2$s(String[] path, String name, %3$s va, %3$s vb) {
                        this.path = path;
                        this.name = name;
                        this.va = va;
                        this.vb = vb;
                    }

                    @Override
                    public boolean test(StructAccessor row) {
                        StructAccessor s = RecordFilterCompiler.resolve(row, path);
                        if (s == null || s.isNull(name)) {
                            return false;
                        }
                        %3$s v = s.%4$s(name);
                        return %5$s %6$s %7$s;
                    }
                }
                """.formatted(PACKAGE, simpleName, prim, getter, cmpA, connectiveOp, cmpB);
    }

    // ==================== Matrix model ====================

    private enum PrimType {
        INT("int", "Int"),
        LONG("long", "Long"),
        DOUBLE("double", "Double");

        final String primName;
        final String boxedName;

        PrimType(String primName, String boxedName) {
            this.primName = primName;
            this.boxedName = boxedName;
        }

        /// Renders a comparison between `lhs` (the loaded primitive) and `rhs`
        /// (a constant operand) for op `op`. Doubles use `Double.compare` to
        /// preserve the legacy NaN ordering used by [RecordFilterEvaluator].
        String compare(String lhs, String rhs, Op op) {
            if (this == DOUBLE) {
                return switch (op) {
                    case EQ -> "Double.compare(" + lhs + ", " + rhs + ") == 0";
                    case LT -> "Double.compare(" + lhs + ", " + rhs + ") < 0";
                    case LTE -> "Double.compare(" + lhs + ", " + rhs + ") <= 0";
                    case GT -> "Double.compare(" + lhs + ", " + rhs + ") > 0";
                    case GTE -> "Double.compare(" + lhs + ", " + rhs + ") >= 0";
                };
            }
            return lhs + " " + op.token + " " + rhs;
        }
    }

    private enum Op {
        EQ("==", "Eq"),
        LT("<", "Lt"),
        LTE("<=", "Lte"),
        GT(">", "Gt"),
        GTE(">=", "Gte");

        final String token;
        final String camel;

        Op(String token, String camel) {
            this.token = token;
            this.camel = camel;
        }
    }

    private enum Connective {
        AND("And"),
        OR("Or");

        final String camel;

        Connective(String camel) {
            this.camel = camel;
        }
    }

    private record Tuple(PrimType type, Connective connective, Op opA, Op opB) {
        String className(boolean named) {
            String base = "Fused" + type.boxedName + connective.camel + "CsCs_" + opA.camel + opB.camel;
            return named ? base + "_Named" : base;
        }
    }
}
